---
title: "Check Gender"
output: html_notebook
---

Use the gender package to estimate gender.

```{r gender_function}
library(gender)
guess_gender <- function(fn, birth_year = NULL) {
  fn <- str_replace(fn, "^.\\.* ", "")
  if (fn == "") return("")
  if (is.null(birth_year)) return(gender(str_split(fn, " ")[[1]][1]))
  if (is.na(birth_year)) return(gender(str_split(fn, " ")[[1]][1]))
  gender::gender(str_split(fn, " ")[[1]][1], birth_year)
}
```

```{r}
ll <- regs %>% 
  mutate(yob = as.numeric(str_extract(text_dob, "\\d\\d\\d\\d")),
         fn = map2_chr(str_split(str_replace(first_name, "^.\\. ", ""), " "), 1, first)) %>%
  select(first_name, last_name, fn, text_dob, yob) 
fn_year <- ll %>% select(fn, yob) %>% 
  mutate(yob = (yob %/% 5) * 5) %>%
  unique()
all_fn <- unique(fn_year$fn)
simple_gender <- gender(all_fn)
iffy_gender <- simple_gender %>% filter(proportion_male < 0.6, proportion_male > 0.4) %>%
  mutate(how_close = abs(proportion_male - 0.5)) %>% arrange(desc(how_close))
ll %>% filter(fn %in% iffy_gender$name) %>% select(proportion_male)
```




